name: Student tests
on: [pull_request]
jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TRAVIS_BRANCH: ${{github.base_ref}}
      TRAVIS_COMMIT_RANGE: HEAD^..HEAD
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Tests
        run: test/travis.sh
